endpoint: https://api.aimlapi.com/v1
model: meta-llama/Meta-Llama-3-70B-Instruct-Turbo
api_key: your_api_key
openai_api_key: your_api_key

# If the main model is from aimlapi, you should specify api_key to be aimlapi key. openai_api_key is used for cross-verification.